language: cpp
dist: xenial
addons:
  sonarcloud:
    organization: "yuui-tanabe-github"
  apt:
    packages:
      - libspdlog-dev
script:
  - cmake -G"Unix Makefiles" .
  - build-wrapper-linux-x86-64 --out-dir bw_output CXXFLAGS="-std=c++11" make clean all
  - sonar-scanner
