language: cpp
addons:
  sonarcloud:
    organization: "yuui-tanabe-github"
script:
  - cmake -G"Unix Makefiles" .
  - make
  - sonar-scanner -Dsonar.sources=. -Dsonar.projectKey=yuui-tanabe_helloworld
