language: cpp
addons:
  sonarcloud:
    organization: "yuui-tanabe-github"
    projectKey: "yuui-tanabe_helloworld"
    sources: .
    
script:
  - cmake -G"Unix Makefiles" .
  - make
  - sonar-scanner
