version: 2
jobs:
  build:
    docker:
      - image: archlinux/base
    steps:
      - run:
          name: Install Tools
          command: pacman -Syu --noconfirm
          command: pacman -Sy --noconfirm make gcc cmake git openssh
      - checkout
      - run:
          name: Compile
          command: cmake . -G"Unix Makefiles" && make
