version: 2
jobs:
  build:
    docker:
      - image: archlinux/base
    steps:
      - checkout
      - run:
          name: Update Keyring
          command: pacman -Syu
          command: rm -rf /etc/pacman.d/gnupg
          command: pacman-key --init
          command: pacman-key --populate archlinux
          

      - run:
          name: Install Tools
          command: pacman -Sy make gcc
      - run:
          name: Compile
          command: make
