version: 2
jobs:
  build:
    docker:
      - image: archlinux/base
    steps:
      - checkout
      - run:
          name: Install Tools
          command: pacman -Syu --noconfirm
          command: pacman -Sy --noconfirm make gcc
      - run:
          name: Compile
          command: make
