version: 2
jobs:
  build:
    docker:
      - image: archlinux/base
    steps:
      - run:
          name: Install Tools
          command: pacman -Syu --noconfirm --noprogressbar && pacman -Sy --noconfirm --noprogressbar make gcc cmake git openssh
      - checkout
      - run:
          name: Compile
          command: cmake . -G"Unix Makefiles" && make && mv helloworld $CIRCLE_ARTIFACTS
